-- Phase 3A: Parish-tier vendors, bills, approvals, and payments.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS accounting_payment_terms(id TEXT PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,due_days INTEGER NOT NULL DEFAULT 0,discount_days INTEGER NOT NULL DEFAULT 0,discount_percent_basis_points INTEGER NOT NULL DEFAULT 0,is_default INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),version INTEGER NOT NULL DEFAULT 1,CHECK(due_days>=0),CHECK(discount_percent_basis_points BETWEEN 0 AND 10000));
INSERT OR IGNORE INTO accounting_payment_terms(id,code,name,due_days,is_default) VALUES('terms_due','DUE_ON_RECEIPT','Due on receipt',0,0),('terms_net30','NET_30','Net 30',30,1);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ap_terms_default ON accounting_payment_terms(is_default) WHERE is_default=1 AND is_active=1;
CREATE TABLE IF NOT EXISTS accounting_vendors(id TEXT PRIMARY KEY,vendor_number TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,legal_name TEXT,vendor_type TEXT NOT NULL DEFAULT 'business',status TEXT NOT NULL DEFAULT 'active',email TEXT,phone TEXT,website TEXT,address_line1 TEXT,address_line2 TEXT,city TEXT,state_region TEXT,postal_code TEXT,country TEXT NOT NULL DEFAULT 'US',payment_terms_id TEXT,default_expense_account_id TEXT,default_fund_id TEXT,default_payment_method TEXT,tax_classification TEXT,tax_id_last4 TEXT,requires_1099_review INTEGER NOT NULL DEFAULT 0,notes TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),archived_at TEXT,version INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(payment_terms_id) REFERENCES accounting_payment_terms(id),FOREIGN KEY(default_expense_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(default_fund_id) REFERENCES accounting_funds(id),CHECK(vendor_type IN('business','individual','clergy','government','utility','diocese','monastery','charity','other')),CHECK(status IN('active','inactive','archived','blocked')),CHECK(tax_id_last4 IS NULL OR length(tax_id_last4)<=4));
CREATE INDEX IF NOT EXISTS idx_ap_vendors_name ON accounting_vendors(display_name,status);
CREATE TABLE IF NOT EXISTS accounting_bills(id TEXT PRIMARY KEY,bill_number TEXT NOT NULL UNIQUE,vendor_id TEXT NOT NULL,vendor_invoice_number TEXT,bill_date TEXT NOT NULL,received_date TEXT,due_date TEXT NOT NULL,posting_date TEXT,description TEXT NOT NULL,memo TEXT,currency TEXT NOT NULL DEFAULT 'USD',status TEXT NOT NULL DEFAULT 'draft',approval_status TEXT NOT NULL DEFAULT 'pending',payment_status TEXT NOT NULL DEFAULT 'unpaid',subtotal_amount INTEGER NOT NULL DEFAULT 0,tax_amount INTEGER NOT NULL DEFAULT 0,total_amount INTEGER NOT NULL DEFAULT 0,amount_paid INTEGER NOT NULL DEFAULT 0,amount_due INTEGER NOT NULL DEFAULT 0,accounts_payable_account_id TEXT NOT NULL DEFAULT 'acct_2000',created_by_actor_type TEXT NOT NULL,created_by_actor_id TEXT NOT NULL,submitted_by_actor_type TEXT,submitted_by_actor_id TEXT,approved_by_actor_type TEXT,approved_by_actor_id TEXT,posted_journal_entry_id TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),submitted_at TEXT,approved_at TEXT,posted_at TEXT,voided_at TEXT,version INTEGER NOT NULL DEFAULT 1,correlation_id TEXT,FOREIGN KEY(vendor_id) REFERENCES accounting_vendors(id),FOREIGN KEY(accounts_payable_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(posted_journal_entry_id) REFERENCES accounting_journal_entries(id),CHECK(status IN('draft','submitted','approved','posted','partially_paid','paid','rejected','voided')),CHECK(approval_status IN('not_required','pending','approved','rejected')),CHECK(payment_status IN('unpaid','scheduled','partially_paid','paid','failed')),CHECK(total_amount>=0 AND amount_paid>=0 AND amount_due>=0));
CREATE UNIQUE INDEX IF NOT EXISTS idx_ap_bill_vendor_invoice ON accounting_bills(vendor_id,vendor_invoice_number) WHERE vendor_invoice_number IS NOT NULL AND vendor_invoice_number<>'' AND status<>'voided';
CREATE TABLE IF NOT EXISTS accounting_bill_lines(id TEXT PRIMARY KEY,bill_id TEXT NOT NULL,line_number INTEGER NOT NULL,description TEXT NOT NULL,account_id TEXT NOT NULL,fund_id TEXT NOT NULL,quantity INTEGER NOT NULL DEFAULT 1,unit_amount INTEGER NOT NULL,line_amount INTEGER NOT NULL,tax_amount INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(bill_id) REFERENCES accounting_bills(id),FOREIGN KEY(account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(fund_id) REFERENCES accounting_funds(id),UNIQUE(bill_id,line_number),CHECK(quantity>0 AND unit_amount>=0 AND line_amount>=0 AND tax_amount>=0));
CREATE TABLE IF NOT EXISTS accounting_bill_approvals(id TEXT PRIMARY KEY,bill_id TEXT NOT NULL,sequence_number INTEGER NOT NULL,actor_type TEXT NOT NULL,actor_id TEXT NOT NULL,decision TEXT NOT NULL,reason TEXT,decided_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(bill_id) REFERENCES accounting_bills(id),CHECK(decision IN('approved','rejected')));
CREATE TABLE IF NOT EXISTS accounting_payments(id TEXT PRIMARY KEY,payment_number TEXT NOT NULL UNIQUE,vendor_id TEXT NOT NULL,payment_date TEXT NOT NULL,payment_method TEXT NOT NULL,bank_account_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',currency TEXT NOT NULL DEFAULT 'USD',total_amount INTEGER NOT NULL,reference_number TEXT,check_number TEXT,memo TEXT,scheduled_at TEXT,processed_at TEXT,cleared_at TEXT,voided_at TEXT,created_by_actor_type TEXT NOT NULL,created_by_actor_id TEXT NOT NULL,approved_by_actor_type TEXT,approved_by_actor_id TEXT,posted_journal_entry_id TEXT,reconciliation_transaction_id TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),version INTEGER NOT NULL DEFAULT 1,correlation_id TEXT,FOREIGN KEY(vendor_id) REFERENCES accounting_vendors(id),FOREIGN KEY(bank_account_id) REFERENCES accounting_bank_accounts(id),FOREIGN KEY(posted_journal_entry_id) REFERENCES accounting_journal_entries(id),CHECK(payment_method IN('check','ach','wire','debit_card','credit_card','cash','external','other')),CHECK(status IN('draft','scheduled','approved','posted','cleared','failed','voided')),CHECK(total_amount>0));
CREATE UNIQUE INDEX IF NOT EXISTS idx_ap_check_number ON accounting_payments(bank_account_id,check_number) WHERE check_number IS NOT NULL AND check_number<>'' AND status<>'voided';
CREATE TABLE IF NOT EXISTS accounting_payment_applications(id TEXT PRIMARY KEY,payment_id TEXT NOT NULL,bill_id TEXT NOT NULL,amount_applied INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(payment_id) REFERENCES accounting_payments(id),FOREIGN KEY(bill_id) REFERENCES accounting_bills(id),UNIQUE(payment_id,bill_id),CHECK(amount_applied>0));
CREATE TABLE IF NOT EXISTS accounting_recurring_bills(id TEXT PRIMARY KEY,vendor_id TEXT NOT NULL,name TEXT NOT NULL,frequency TEXT NOT NULL,next_run_date TEXT NOT NULL,end_date TEXT,payment_terms_id TEXT,default_description TEXT,auto_create_draft INTEGER NOT NULL DEFAULT 1,requires_review INTEGER NOT NULL DEFAULT 1,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),version INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(vendor_id) REFERENCES accounting_vendors(id),FOREIGN KEY(payment_terms_id) REFERENCES accounting_payment_terms(id),CHECK(frequency IN('weekly','monthly','quarterly','annual','custom_interval')));
