-- Phase 3B: Parish-tier budgeting and forecasting.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS accounting_budgets(id TEXT PRIMARY KEY,budget_name TEXT NOT NULL,fiscal_year_id TEXT NOT NULL,version_number INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft',description TEXT,revision_notes TEXT,created_by TEXT NOT NULL,approved_by TEXT,locked_by TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),submitted_at TEXT,approved_at TEXT,locked_at TEXT,version INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(fiscal_year_id) REFERENCES accounting_fiscal_years(id),UNIQUE(fiscal_year_id,version_number),CHECK(version_number>0),CHECK(status IN('draft','submitted','approved','locked','archived')));
CREATE UNIQUE INDEX IF NOT EXISTS idx_budget_official ON accounting_budgets(fiscal_year_id) WHERE status='locked';
CREATE TABLE IF NOT EXISTS accounting_budget_lines(id TEXT PRIMARY KEY,budget_id TEXT NOT NULL,account_id TEXT NOT NULL,fund_id TEXT NOT NULL,annual_amount INTEGER NOT NULL,january_amount INTEGER NOT NULL DEFAULT 0,february_amount INTEGER NOT NULL DEFAULT 0,march_amount INTEGER NOT NULL DEFAULT 0,april_amount INTEGER NOT NULL DEFAULT 0,may_amount INTEGER NOT NULL DEFAULT 0,june_amount INTEGER NOT NULL DEFAULT 0,july_amount INTEGER NOT NULL DEFAULT 0,august_amount INTEGER NOT NULL DEFAULT 0,september_amount INTEGER NOT NULL DEFAULT 0,october_amount INTEGER NOT NULL DEFAULT 0,november_amount INTEGER NOT NULL DEFAULT 0,december_amount INTEGER NOT NULL DEFAULT 0,allocation_strategy TEXT NOT NULL DEFAULT 'manual',notes TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),version INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(budget_id) REFERENCES accounting_budgets(id),FOREIGN KEY(account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(fund_id) REFERENCES accounting_funds(id),UNIQUE(budget_id,account_id,fund_id),CHECK(annual_amount>=0),CHECK(allocation_strategy IN('even_monthly','prior_year_actuals','manual','seasonal','percentage')),
CHECK(annual_amount=january_amount+february_amount+march_amount+april_amount+may_amount+june_amount+july_amount+august_amount+september_amount+october_amount+november_amount+december_amount));
CREATE INDEX IF NOT EXISTS idx_budget_lines_report ON accounting_budget_lines(budget_id,fund_id,account_id);
CREATE TABLE IF NOT EXISTS accounting_budget_assumptions(id TEXT PRIMARY KEY,budget_id TEXT NOT NULL,sort_order INTEGER NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(budget_id) REFERENCES accounting_budgets(id));
CREATE TABLE IF NOT EXISTS accounting_budget_events(id TEXT PRIMARY KEY,budget_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_id TEXT NOT NULL,reason TEXT,metadata_json TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(budget_id) REFERENCES accounting_budgets(id));
CREATE TRIGGER IF NOT EXISTS accounting_locked_budget_immutable BEFORE UPDATE ON accounting_budgets WHEN OLD.status='locked' BEGIN SELECT RAISE(ABORT,'locked budget is immutable'); END;
CREATE TRIGGER IF NOT EXISTS accounting_locked_budget_lines_no_insert BEFORE INSERT ON accounting_budget_lines WHEN (SELECT status FROM accounting_budgets WHERE id=NEW.budget_id)='locked' BEGIN SELECT RAISE(ABORT,'locked budget lines are immutable'); END;
CREATE TRIGGER IF NOT EXISTS accounting_locked_budget_lines_no_update BEFORE UPDATE ON accounting_budget_lines WHEN (SELECT status FROM accounting_budgets WHERE id=OLD.budget_id)='locked' BEGIN SELECT RAISE(ABORT,'locked budget lines are immutable'); END;
CREATE TRIGGER IF NOT EXISTS accounting_locked_budget_lines_no_delete BEFORE DELETE ON accounting_budget_lines WHEN (SELECT status FROM accounting_budgets WHERE id=OLD.budget_id)='locked' BEGIN SELECT RAISE(ABORT,'locked budget lines are immutable'); END;
