-- Phase 3C: Parish Commerce accounting and inventory readiness.
PRAGMA foreign_keys=ON;
INSERT OR IGNORE INTO accounting_accounts(id,account_number,name,account_type_id,normal_balance,is_posting_account,is_system,requires_fund) VALUES
('acct_1020','1020','Cash on Hand','type_asset','debit',1,1,1),('acct_1120','1120','External Processor Clearing','type_asset','debit',1,1,1),
('acct_1200','1200','Bookstore Inventory','type_asset','debit',1,1,1),('acct_2100','2100','Sales Tax Payable','type_liability','credit',1,1,1),
('acct_4050','4050','Other Commerce Revenue','type_revenue','credit',1,1,1),('acct_4320','4320','Sales Returns and Allowances','type_revenue','credit',1,1,1);
ALTER TABLE accounting_integration_source_events ADD COLUMN commerce_channel TEXT;
ALTER TABLE accounting_integration_source_events ADD COLUMN order_number TEXT;
ALTER TABLE accounting_integration_source_events ADD COLUMN tender_type TEXT;
ALTER TABLE accounting_integration_source_events ADD COLUMN gross_merchandise_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounting_integration_source_events ADD COLUMN discount_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounting_integration_source_events ADD COLUMN taxable_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounting_integration_source_events ADD COLUMN tax_exempt_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounting_integration_source_events ADD COLUMN sales_tax_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounting_integration_source_events ADD COLUMN shipping_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounting_integration_source_events ADD COLUMN tip_or_donation_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounting_integration_source_events ADD COLUMN tax_jurisdiction TEXT;
ALTER TABLE accounting_integration_source_events ADD COLUMN tax_rate_basis_points INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS accounting_commerce_settings(id TEXT PRIMARY KEY CHECK(id='primary'),posting_mode TEXT NOT NULL DEFAULT 'review_required',integration_start_date TEXT,default_revenue_account_id TEXT NOT NULL DEFAULT 'acct_4300',sales_tax_liability_account_id TEXT NOT NULL DEFAULT 'acct_2100',fee_expense_account_id TEXT NOT NULL DEFAULT 'acct_5840',stripe_clearing_account_id TEXT NOT NULL DEFAULT 'acct_1110',cash_account_id TEXT NOT NULL DEFAULT 'acct_1100',external_clearing_account_id TEXT NOT NULL DEFAULT 'acct_1120',refund_account_id TEXT NOT NULL DEFAULT 'acct_4320',inventory_asset_account_id TEXT NOT NULL DEFAULT 'acct_1200',cogs_account_id TEXT NOT NULL DEFAULT 'acct_5700',default_fund_id TEXT NOT NULL DEFAULT 'fund_general',negative_inventory_policy TEXT NOT NULL DEFAULT 'exception',settings_version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL DEFAULT(datetime('now')),CHECK(posting_mode IN('automatic','review_required')),CHECK(negative_inventory_policy IN('block','exception','allow_with_override')));
INSERT OR IGNORE INTO accounting_commerce_settings(id) VALUES('primary');
CREATE TABLE IF NOT EXISTS accounting_commerce_mappings(id TEXT PRIMARY KEY,commerce_channel TEXT,revenue_stream_id TEXT,settlement_profile_id TEXT,item_id TEXT,item_category_id TEXT,tax_category_id TEXT,revenue_account_id TEXT,sales_tax_liability_account_id TEXT,fee_expense_account_id TEXT,clearing_account_id TEXT,refund_account_id TEXT,inventory_asset_account_id TEXT,cogs_account_id TEXT,fund_id TEXT,is_inventory_tracked INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,effective_from TEXT,effective_to TEXT,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(revenue_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(sales_tax_liability_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(fee_expense_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(clearing_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(refund_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(inventory_asset_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(cogs_account_id) REFERENCES accounting_accounts(id),FOREIGN KEY(fund_id) REFERENCES accounting_funds(id));
CREATE INDEX IF NOT EXISTS idx_commerce_mapping_precedence ON accounting_commerce_mappings(item_id,item_category_id,revenue_stream_id,settlement_profile_id,commerce_channel,is_active);
CREATE TABLE IF NOT EXISTS accounting_commerce_items(id TEXT PRIMARY KEY,operational_item_id TEXT NOT NULL UNIQUE,sku TEXT,barcode TEXT,name TEXT NOT NULL,category_id TEXT,revenue_stream_id TEXT,default_revenue_account_id TEXT,default_fund_id TEXT,tax_category_id TEXT,is_taxable INTEGER NOT NULL DEFAULT 0,is_inventory_tracked INTEGER NOT NULL DEFAULT 0,inventory_asset_account_id TEXT,cogs_account_id TEXT,current_unit_cost INTEGER,costing_method TEXT NOT NULL DEFAULT 'manual_cost',quantity_on_hand INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),version INTEGER NOT NULL DEFAULT 1,CHECK(current_unit_cost IS NULL OR current_unit_cost>=0),CHECK(costing_method IN('average_cost','manual_cost')));
CREATE UNIQUE INDEX IF NOT EXISTS idx_commerce_item_sku ON accounting_commerce_items(sku) WHERE sku IS NOT NULL AND sku<>'';
CREATE UNIQUE INDEX IF NOT EXISTS idx_commerce_item_barcode ON accounting_commerce_items(barcode) WHERE barcode IS NOT NULL AND barcode<>'';
CREATE TABLE IF NOT EXISTS accounting_commerce_source_items(id TEXT PRIMARY KEY,source_event_id TEXT NOT NULL,operational_item_id TEXT NOT NULL,sku_snapshot TEXT,barcode_snapshot TEXT,name_snapshot TEXT NOT NULL,quantity INTEGER NOT NULL,gross_amount INTEGER NOT NULL,discount_amount INTEGER NOT NULL DEFAULT 0,tax_amount INTEGER NOT NULL DEFAULT 0,refund_amount INTEGER NOT NULL DEFAULT 0,unit_cost_snapshot INTEGER,is_resalable_return INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(source_event_id) REFERENCES accounting_integration_source_events(id),UNIQUE(source_event_id,operational_item_id),CHECK(quantity>0));
CREATE TABLE IF NOT EXISTS accounting_inventory_movements(id TEXT PRIMARY KEY,item_id TEXT NOT NULL,movement_type TEXT NOT NULL,quantity INTEGER NOT NULL,unit_cost INTEGER,total_cost INTEGER,source_type TEXT NOT NULL,source_id TEXT NOT NULL,occurred_at TEXT NOT NULL,journal_entry_id TEXT,reversal_movement_id TEXT,status TEXT NOT NULL DEFAULT 'committed',created_at TEXT NOT NULL DEFAULT(datetime('now')),correlation_id TEXT,FOREIGN KEY(item_id) REFERENCES accounting_commerce_items(id),FOREIGN KEY(journal_entry_id) REFERENCES accounting_journal_entries(id),UNIQUE(source_type,source_id,item_id,movement_type),CHECK(movement_type IN('sale','return','purchase_future','adjustment_increase','adjustment_decrease','damage','loss','opening_quantity','count_correction')),CHECK(quantity<>0),CHECK(status IN('pending_cost','committed','exception','reversed')));
