name = "agapay-site"
main = "src/worker.js"
compatibility_date = "2026-05-25"

[vars]
AGAPAY_FROM_EMAIL = "AgaPay <onboarding@agapay.app>"
AGAPAY_REPLY_TO_EMAIL = "support@agapay.app"
AGAPAY_REGISTRATION_NOTIFY_EMAIL = "hellp@agapay.app"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "AGAPAY_REGISTRATIONS"
id = "c0c630d2699a4d42a72db927c6341707"

[secrets]
required = [
  "AGAPAY_ADMIN_TOKEN"
]
