name = "agapay-site"
main = "src/worker.js"
compatibility_date = "2026-05-25"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "AGAPAY_REGISTRATIONS"
id = "c0c630d2699a4d42a72db927c6341707"
