import { getBearerToken, handleSecurityConfig, json, unauthorized, corsJson } from '../lib/core.js';
import {
  handleAdminNonprofitPricing,
  handleAdminNonprofitPricingAlerts,
  handleAdminNonprofitPricingDocumentView,
  handleParishNonprofitPricing,
  handleParishNonprofitPricingDocumentUpload,
  handleParishNonprofitPricingDocumentView,
} from '../handlers/nonprofit-pricing.js';
import { handleOperationsCanary, handleOperationsMonitorAlert } from '../operations/monitoring.js';
import { handleAdminDailyPastoralCareDigest } from '../sacraments/pastoral-digest.js';
import {
  verifyParishDashboardBearer,
  findRegistrationByParishId,
  handleParishStripeRefresh,
  handleDashboardInvite,
  handleParishStripeOnboarding,
  handleParishSubscriptionCheckout,
  handleParishDemoTier,
  handleParishSubscriptionRefresh,
  handleParishSubscriptionPortal,
  handleParishDashboard,
  handleParishFeatureRequestDismiss,
  handleParishSession,
  handleRegistrations,
  handleCheckout,
  handleCheckoutSessionStatus,
  handleParishPasswordResetRequest,
  handleParishPasswordResetConfirm,
  requireDonor,
} from '../handlers/parish.js';
import { handleParishOnboarding } from '../handlers/parish-onboarding.js';
import {
  handleParishGivingHistory,
  handleParishGivingSummary,
  handleParishRecurringHealth,
  handleParishStripeVolume,
} from '../handlers/parish-giving-reports.js';
import {
  handleParishPayoutDiagnostics,
  handleParishReconciliation,
  handleParishReconciliationClose,
} from '../handlers/parish-reconciliation.js';
import {
  handleParishes,
  handleParishCampaignUpload,
  handleParishLogo,
  handlePublicCampaign,
  handlePublicPlatformSummary,
} from '../handlers/parish-giving-catalog.js';
import { handleParishBookstore, handleParishSettlementProfiles } from '../handlers/parish-commerce.js';
import {
  handleAdminSetSacramentsEnabled,
  handleParishAvailabilityBlackoutCreate,
  handleParishAvailabilityBlackoutDelete,
  handleParishAvailabilityRuleCreate,
  handleParishAvailabilityRuleDelete,
  handleParishCommemorations,
  handleParishSacramentAvailability,
  handleParishSacramentUpdate,
  handleParishSacraments,
} from '../handlers/parish-sacraments.js';
import {
  handleSacramentsGoogleCallback,
  handleSacramentsGoogleConnect,
  handleSacramentsGoogleDisconnect,
  handleSacramentsGoogleStatus,
} from '../sacraments/google-calendar.js';
import {
  handleDonorSacramentPreparation,
  handleParishSacramentPreparation,
} from '../handlers/sacrament-preparation.js';
import { handleParishPastoralFollowUp } from '../handlers/parish-pastoral-followup.js';
import {
  handleDonorClaimCheckout,
  handleDonorSession,
  handleDonorPasswordResetRequest,
  handleDonorPasswordResetConfirm,
  handleDonorSignup,
  handleDonorLogin,
  handleDonorVerify,
  handleDonorVerifyPage,
  handleDonorDashboard,
  handleDonorSupportTicket,
  handleDonorAccountDeletion,
  handleDonorParishCalendar,
  handleDonorGivingPlusFeatureRequest,
  handleDonorMinistryServiceInterest,
  handleDonorStewardshipFeatureRequest,
  handleDonorOfferings,
  handleDonorSubscriptionPortal,
  handleDonorBookstore,
  handleParishBookstoreReadiness,
  handleDonorBookstoreItemFields,
  handleDonorBookstoreIsbnLookup,
  handleDonorBookstoreRequestFeature,
  handleDonorCommemorations,
  handleDonorSacraments,
  handleDonorSacramentAvailability,
  handleDonorSacramentBook,
  handleDonorSacramentCancel,
  handleDonorNotifications,
  handleDonorNotificationDismiss,
} from '../handlers/donor.js';
import { handleDonorEvents, handleParishEvents } from '../handlers/parish-events.js';
import {
  handleConsumerPasskeyAuthenticationOptions,
  handleConsumerPasskeyAuthenticationVerify,
  handleConsumerPasskeyRegistrationOptions,
  handleConsumerPasskeyRegistrationVerify,
  handleConsumerPasskeys,
} from '../handlers/consumer-passkeys.js';
import {
  handleAnnouncementDigestUnsubscribe,
  handleDonorDigestSubscription,
  handleDonorFeed,
  handleParishCommunications,
} from '../handlers/parish-communications.js';
import { handleParishBulletins } from '../handlers/parish-bulletins.js';
import { handleDonorGroups } from '../handlers/donor-groups.js';
import { handleKoinoniaAccess } from '../handlers/koinonia-access.js';
import { handleDonorKoinoniaCommunityTools } from '../handlers/koinonia-community-tools.js';
import { handleDonorKoinoniaSignups } from '../handlers/koinonia-signups.js';
import { handleDonorKoinoniaExchange } from '../handlers/koinonia-exchange.js';
import { handleDonorKoinoniaPrayerRequests, handleParishPrayerRequests } from '../handlers/koinonia-prayer-requests.js';
import { handleDonorTeaching, handleParishTeaching } from '../handlers/parish-teaching.js';
import { handlePublicParishAsset } from '../handlers/public-parish-assets.js';
import { handleDonorParishLibrary, handleParishLibrary } from '../handlers/parish-library.js';
import { handleDonorVideo, handleParishVideo } from '../handlers/parish-video.js';
import {
  handleDonorBlog,
  handleDonorCustomNewsFeeds,
  handleDonorExternalFeed,
  handleDonorOcaNews,
  handleParishBlog,
} from '../handlers/parish-blog.js';
import { handleDonorPush } from '../lib/push-notifications.js';
import { publicSubscriptionTiers } from '../lib/subscriptions.js';
import {
  handleAdminRegistrations,
  handleAdminSession,
  handleAdminMigrateKvToD1,
  handleAdminPlatformSummary,
  handleAdminRegistrationGivingSummary,
  handleAdminLearnScholarship,
  handleAdminLearnCommunity,
  handleAdminLearnSummary,
  handleAdminReleaseStatus,
  handleAdminEmailDiagnostics,
  handleAdminAuditLog,
  handleAdminRebuildIndexes,
  handleAdminPassword,
  handleAdminRegistrationDetail,
  handleAdminOnboardingTest,
  handleAdminLearnFeedback,
  handleAdminParishSupportTickets,
  handleAdminAccountingOperations,
} from '../handlers/admin.js';
import { handleResendWebhook } from '../handlers/resend-webhook.js';
import { handleSubscriptionCheckout, handleStripeWebhook, handleStripeRefresh } from '../handlers/stripe.js';
import {
  handleParishStewardshipBillingPortal,
  handleParishStewardshipMeetingDetail,
  handleParishStewardshipMeetings,
  handleParishStewardshipSubscribe,
  handleParishStewardshipSummary,
  handleStewardshipHome,
  handleStewardshipSubscribe,
  handleStewardshipBilling,
  handleStewardshipBillingPortal,
  handleStewardshipMeetingList,
  handleStewardshipMeetingNew,
  handleStewardshipMeetingEdit,
  handleStewardshipMeetingPreview,
  handleStewardshipMeetingPdf,
  handleStewardshipWebhook,
  handleStewardshipGivingMetricsPage,
  handleStewardshipFinancials,
  handleStewardshipNudge,
  handleAdminGrantStewardshipComp,
  handleAdminStewardshipCompStatus,
} from '../handlers/stewardship.js';
import { handleStewardshipAccountingBridge } from '../handlers/stewardship-accounting-bridge.js';
import {
  handleStewardshipAttendance,
  handleStewardshipAttendanceDelegation,
} from '../handlers/stewardship-attendance.js';
import { handleDiocesanStatisticsReport } from '../handlers/diocesan-statistics.js';
import {
  handleGivingStatementPreview,
  handleGivingStatementJobCreate,
  handleGivingStatementJobStatus,
  handleGivingStatementJobList,
  handleDonorGivingStatements,
  handleDonorGivingStatementDownload,
} from '../handlers/giving-statements.js';
import {
  handleLearnBooks,
  handleLearnCommunity,
  handleLearnCommunityFlag,
  handleLearnCommunitySubmit,
  handleLearnCompletionSave,
  handleLearnCoOp,
  handleLearnDashboard,
  handleLearnFeedbackSubmit,
  handleLearnFormation,
  handleLearnFamilyPlanningSave,
  handleLearnAttendanceSave,
  handleLearnGrades,
  handleLearnGradesSave,
  handleLearnTestScores,
  handleLearnTestScoresSave,
  handleLearnGraceModeSave,
  handleLearnMoveUnfinishedWork,
  handleLearnPlannerBlockSave,
  handleLearnBillingCancel,
  handleLearnBillingCheckout,
  handleLearnBillingStatus,
  handleLearnGoogleCalendarCallback,
  handleLearnGoogleCalendarConnect,
  handleLearnGoogleCalendarPreview,
  handleLearnGoogleCalendarStatus,
  handleLearnGoogleCalendarSync,
  handleLearnMeta,
  handleLearnOnboarding,
  handleLearnOnboardingSave,
  handleLearnPlanner,
  handleLearnPrintCenter,
  handleLearnPrintPdf,
  handleLearnReports,
  handleLearnSaints,
  handleLearnTermClose,
} from '../learn/handlers.js';
import {
  handleTaxExemptionStateGuidance,
  handleClaimScopedDocumentUpload,
  handleParishTaxExemptionClaim,
  handleParishTaxExemptionDocumentUpload,
  handleParishTaxExemptionDocumentView,
  handleAdminTaxExemptionQueue,
  handleAdminTaxExemptionSummary,
  handleAdminTaxExemptionDetail,
  handleAdminTaxExemptionApprove,
  handleAdminTaxExemptionReject,
  handleAdminTaxExemptionRequestReplacement,
  handleAdminTaxExemptionRevoke,
  handleAdminTaxExemptionExpire,
  handleAdminTaxExemptionRetrySync,
  handleAdminTaxExemptionSyncRetry,
  handleAdminTaxExemptionSyncReconcile,
  handleAdminTaxExemptionDocumentView,
  handleAdminTaxExemptionNote,
} from '../handlers/tax-exemption.js';
import { handleParishInterest } from '../handlers/parish-interest.js';
import {
  handleListenProgress,
  handleListenSubscriptions,
  handleListenSearch,
  handleListenRss,
  handleListenAudio,
} from '../handlers/listen.js';
import { handleMarketplaceCatalog } from '../handlers/marketplace.js';
import { handleDirectorySelfService } from '../handlers/directory-self-service.js';
import { handleDirectoryMedia } from '../handlers/directory-media.js';
import { handleDirectoryMember } from '../handlers/directory-member.js';
import { handleDirectoryAdmin } from '../handlers/directory-admin.js';
import { handleAccountingLedger } from '../handlers/accounting-ledger.js';
import { handleAccountingMigration } from '../handlers/accounting-migration.js';
import { handleAccountingAttachments } from '../handlers/accounting-attachments.js';
import { handleAccountingSetupReports } from '../handlers/accounting-setup-reports.js';
import { handleAccountingPayablesBudgets } from '../handlers/accounting-payables-budgets.js';
import { handleAccountingReconciliationCommerce } from '../handlers/accounting-reconciliation-commerce.js';
import { handleAccountingClose } from '../handlers/accounting-close.js';
import { handleAccountingAdjustments } from '../handlers/accounting-adjustments.js';
import { handleAccountingGovernance } from '../handlers/accounting-governance.js';
import { handleAccountingAccess } from '../handlers/accounting-access.js';
import { handleAccountingRecurring } from '../handlers/accounting-recurring.js';
import {
  handleIdentityLogin,
  handleIdentitySession,
  handleIdentityLogout,
  handleIdentityInvitationAccept,
  handleIdentityCapabilityCatalog,
  handleMembershipInvitationCreate,
  handleMembershipInvitationRevoke,
  handleMembershipList,
} from '../handlers/identity.js';
import {
  handleMfaEnrollmentOptions,
  handleMfaEnrollmentVerify,
  handleMfaStatus,
  handleMfaStepUp,
  handleMfaVerify,
} from '../handlers/mfa.js';

import {
  handleDirectoryIntake,
  handleDonorLiturgicalDay,
  handleLiturgicalCalendar,
  handleWaitlist,
} from '../handlers/public-entry.js';
import {
  handleAdminWeeklyAnnouncementDigest,
  handleAdminWeeklyCommemorationEmails,
  handleAdminWeeklySacramentDigest,
  handleAdminWeeklyTreasurerCommerceEmails,
} from '../operations/weekly-email-digests.js';
import {
  addCorsHeaders,
  handleAdminRecentActivity,
  handleStewardshipGivingActivate,
  handleStewardshipGivingConcentration,
  handleStewardshipGivingDistribution,
  handleStewardshipGivingFunds,
  handleStewardshipGivingHealthScore,
  handleStewardshipGivingRecurring,
  handleStewardshipGivingRetention,
  handleStewardshipGivingSummary,
  handleStewardshipManualIncomeCreate,
  handleStewardshipManualIncomeDelete,
  handleStewardshipManualIncomeList,
} from '../handlers/stewardship-giving.js';
import {
  handleStewardshipMonthlyFinancialReport,
  handleStewardshipMonthlyReport,
} from '../handlers/stewardship-reports.js';
import { handleHealth, handleLearnOdysseyActivate } from '../handlers/platform-actions.js';

export const ROUTE_ACTIONS = Object.freeze({
  addCorsHeaders,
  corsJson,
  findRegistrationByParishId,
  getBearerToken,
  handleAdminAccountingOperations,
  handleAdminAuditLog,
  handleAdminEmailDiagnostics,
  handleAdminGrantStewardshipComp,
  handleAdminLearnCommunity,
  handleAdminLearnFeedback,
  handleAdminLearnScholarship,
  handleAdminLearnSummary,
  handleAdminMigrateKvToD1,
  handleAdminNonprofitPricing,
  handleAdminNonprofitPricingAlerts,
  handleAdminNonprofitPricingDocumentView,
  handleAdminOnboardingTest,
  handleAdminParishSupportTickets,
  handleAdminPassword,
  handleAdminPlatformSummary,
  handleAdminRecentActivity,
  handleAdminRebuildIndexes,
  handleAdminRegistrationDetail,
  handleAdminRegistrationGivingSummary,
  handleAdminRegistrations,
  handleAdminReleaseStatus,
  handleAdminSession,
  handleAdminSetSacramentsEnabled,
  handleAdminStewardshipCompStatus,
  handleAdminTaxExemptionApprove,
  handleAdminTaxExemptionDetail,
  handleAdminTaxExemptionDocumentView,
  handleAdminTaxExemptionExpire,
  handleAdminTaxExemptionNote,
  handleAdminTaxExemptionQueue,
  handleAdminTaxExemptionReject,
  handleAdminTaxExemptionRequestReplacement,
  handleAdminTaxExemptionRetrySync,
  handleAdminTaxExemptionRevoke,
  handleAdminTaxExemptionSummary,
  handleAdminTaxExemptionSyncReconcile,
  handleAdminTaxExemptionSyncRetry,
  handleAdminDailyPastoralCareDigest,
  handleAdminWeeklyAnnouncementDigest,
  handleAdminWeeklyCommemorationEmails,
  handleAdminWeeklySacramentDigest,
  handleAdminWeeklyTreasurerCommerceEmails,
  handleAccountingAccess,
  handleAccountingAdjustments,
  handleAccountingAttachments,
  handleAccountingClose,
  handleAccountingGovernance,
  handleAccountingLedger,
  handleAccountingMigration,
  handleAccountingPayablesBudgets,
  handleAccountingReconciliationCommerce,
  handleAccountingRecurring,
  handleAccountingSetupReports,
  handleAnnouncementDigestUnsubscribe,
  handleConsumerPasskeyAuthenticationOptions,
  handleConsumerPasskeyAuthenticationVerify,
  handleConsumerPasskeyRegistrationOptions,
  handleConsumerPasskeyRegistrationVerify,
  handleConsumerPasskeys,
  handleDirectoryAdmin,
  handleDirectoryIntake,
  handleDirectoryMedia,
  handleDirectoryMember,
  handleDirectorySelfService,
  handleClaimScopedDocumentUpload,
  handleDonorAccountDeletion,
  handleDonorBlog,
  handleDonorBookstore,
  handleDonorBookstoreIsbnLookup,
  handleDonorBookstoreItemFields,
  handleDonorBookstoreRequestFeature,
  handleDonorClaimCheckout,
  handleDonorCommemorations,
  handleDonorCustomNewsFeeds,
  handleDonorDashboard,
  handleDonorDigestSubscription,
  handleDonorEvents,
  handleDonorExternalFeed,
  handleDonorFeed,
  handleDonorGivingPlusFeatureRequest,
  handleDonorGivingStatementDownload,
  handleDonorGivingStatements,
  handleDonorGroups,
  handleDonorKoinoniaCommunityTools,
  handleDonorKoinoniaExchange,
  handleDonorKoinoniaPrayerRequests,
  handleDonorKoinoniaSignups,
  handleDonorLogin,
  handleDonorLiturgicalDay,
  handleDonorMinistryServiceInterest,
  handleDonorNotificationDismiss,
  handleDonorNotifications,
  handleDonorOcaNews,
  handleDonorOfferings,
  handleDonorParishCalendar,
  handleDonorParishLibrary,
  handleDonorPasswordResetConfirm,
  handleDonorPasswordResetRequest,
  handleDonorPush,
  handleDonorSacramentAvailability,
  handleDonorSacramentBook,
  handleDonorSacramentCancel,
  handleDonorSacramentPreparation,
  handleDonorSacraments,
  handleDonorSession,
  handleDonorSignup,
  handleDonorStewardshipFeatureRequest,
  handleDonorSubscriptionPortal,
  handleDonorSupportTicket,
  handleDonorTeaching,
  handleDonorVerify,
  handleDonorVerifyPage,
  handleDonorVideo,
  handleKoinoniaAccess,
  handleHealth,
  handleOperationsCanary,
  handleOperationsMonitorAlert,
  handleListenAudio,
  handleListenProgress,
  handleListenRss,
  handleListenSearch,
  handleListenSubscriptions,
  handleLiturgicalCalendar,
  handleMarketplaceCatalog,
  handleDashboardInvite,
  handleIdentityCapabilityCatalog,
  handleIdentityInvitationAccept,
  handleIdentityLogin,
  handleIdentityLogout,
  handleIdentitySession,
  handleMembershipInvitationCreate,
  handleMembershipInvitationRevoke,
  handleMembershipList,
  handleParishAvailabilityBlackoutCreate,
  handleParishAvailabilityBlackoutDelete,
  handleParishAvailabilityRuleCreate,
  handleParishAvailabilityRuleDelete,
  handleParishBlog,
  handleParishBookstore,
  handleParishBookstoreReadiness,
  handleParishBulletins,
  handleParishCampaignUpload,
  handleParishCommemorations,
  handleParishCommunications,
  handleParishDashboard,
  handleParishDemoTier,
  handleParishEvents,
  handleParishFeatureRequestDismiss,
  handleParishGivingHistory,
  handleParishGivingSummary,
  handleParishLibrary,
  handleParishLogo,
  handleParishNonprofitPricing,
  handleParishNonprofitPricingDocumentUpload,
  handleParishNonprofitPricingDocumentView,
  handleParishOnboarding,
  handleParishPasswordResetConfirm,
  handleParishPasswordResetRequest,
  handleParishPastoralFollowUp,
  handleParishPayoutDiagnostics,
  handleParishPrayerRequests,
  handleParishReconciliation,
  handleParishReconciliationClose,
  handleParishRecurringHealth,
  handleParishSacramentAvailability,
  handleParishSacramentPreparation,
  handleParishSacramentUpdate,
  handleParishSacraments,
  handleParishSession,
  handleParishSettlementProfiles,
  handleParishStewardshipBillingPortal,
  handleParishStewardshipMeetingDetail,
  handleParishStewardshipMeetings,
  handleParishStewardshipSubscribe,
  handleParishStewardshipSummary,
  handleParishStripeOnboarding,
  handleParishStripeRefresh,
  handleParishStripeVolume,
  handleParishSubscriptionCheckout,
  handleParishSubscriptionPortal,
  handleParishSubscriptionRefresh,
  handleParishTaxExemptionClaim,
  handleParishTaxExemptionDocumentUpload,
  handleParishTaxExemptionDocumentView,
  handleParishTeaching,
  handleParishVideo,
  handleParishInterest,
  handleParishes,
  handleLearnAttendanceSave,
  handleLearnBillingCancel,
  handleLearnBillingCheckout,
  handleLearnBillingStatus,
  handleLearnBooks,
  handleLearnCommunity,
  handleLearnCommunityFlag,
  handleLearnCommunitySubmit,
  handleLearnCompletionSave,
  handleLearnCoOp,
  handleLearnDashboard,
  handleLearnFamilyPlanningSave,
  handleLearnFeedbackSubmit,
  handleLearnFormation,
  handleLearnGoogleCalendarCallback,
  handleLearnGoogleCalendarConnect,
  handleLearnGoogleCalendarPreview,
  handleLearnGoogleCalendarStatus,
  handleLearnGoogleCalendarSync,
  handleLearnGraceModeSave,
  handleLearnGrades,
  handleLearnGradesSave,
  handleLearnMeta,
  handleLearnMoveUnfinishedWork,
  handleLearnOdysseyActivate,
  handleLearnOnboarding,
  handleLearnOnboardingSave,
  handleLearnPlanner,
  handleLearnPlannerBlockSave,
  handleLearnPrintCenter,
  handleLearnPrintPdf,
  handleLearnReports,
  handleLearnSaints,
  handleLearnTermClose,
  handleLearnTestScores,
  handleLearnTestScoresSave,
  handleSacramentsGoogleCallback,
  handleSacramentsGoogleConnect,
  handleSacramentsGoogleDisconnect,
  handleSacramentsGoogleStatus,
  handlePublicCampaign,
  handlePublicParishAsset,
  handlePublicPlatformSummary,
  handleRegistrations,
  handleResendWebhook,
  handleSecurityConfig,
  handleStripeWebhook,
  handleTaxExemptionStateGuidance,
  handleWaitlist,
  handleMfaEnrollmentOptions,
  handleMfaEnrollmentVerify,
  handleMfaStatus,
  handleMfaStepUp,
  handleMfaVerify,
  handleStripeRefresh,
  handleSubscriptionCheckout,
  handleCheckout,
  handleCheckoutSessionStatus,
  handleGivingStatementJobCreate,
  handleGivingStatementJobList,
  handleGivingStatementJobStatus,
  handleGivingStatementPreview,
  handleStewardshipAccountingBridge,
  handleStewardshipAttendance,
  handleStewardshipAttendanceDelegation,
  handleDiocesanStatisticsReport,
  handleStewardshipBilling,
  handleStewardshipBillingPortal,
  handleStewardshipFinancials,
  handleStewardshipGivingActivate,
  handleStewardshipGivingConcentration,
  handleStewardshipGivingDistribution,
  handleStewardshipGivingFunds,
  handleStewardshipGivingHealthScore,
  handleStewardshipGivingMetricsPage,
  handleStewardshipGivingRecurring,
  handleStewardshipGivingRetention,
  handleStewardshipGivingSummary,
  handleStewardshipHome,
  handleStewardshipManualIncomeCreate,
  handleStewardshipManualIncomeDelete,
  handleStewardshipManualIncomeList,
  handleStewardshipMeetingEdit,
  handleStewardshipMeetingList,
  handleStewardshipMeetingNew,
  handleStewardshipMeetingPdf,
  handleStewardshipMeetingPreview,
  handleStewardshipMonthlyFinancialReport,
  handleStewardshipMonthlyReport,
  handleStewardshipNudge,
  handleStewardshipSubscribe,
  handleStewardshipWebhook,
  json,
  unauthorized,
  verifyParishDashboardBearer,
  publicSubscriptionTiers,
  requireDonor,
});
