import { json } from "../lib/core.js";
import { authorize } from "../lib/authorization.js";
import { accountingEnabledFor, accountingTierFor } from "../lib/entitlements.js";
import { findRegistrationByParishId } from "./parish.js";
import { createCloudflareD1ProvisioningAdapter, createD1DatabaseFacade, createJournalDraft, getJournalEntry, ledgerRegister, ledgerRegisterCsv, loadAccountingDatabaseForEntity, loadAccountingDatabaseProviderRecord, loadAccountingEntityByParish, postJournalEntry, printableLedger, searchJournalEntries, updateJournalDraft, validateJournalEntryForPosting } from "../accounting/index.js";
const HEADERS={"Cache-Control":"private, no-store","X-Robots-Tag":"noindex, nofollow","Vary":"Authorization"};
const reply=(payload,status=200)=>json(payload,{status,headers:HEADERS});
export async function accountingContext(request,env,parishId,capability){const auth=await authorize(request,env,{parishId,capability});if(!auth)return null;const registration=(await findRegistrationByParishId(env,parishId))?.registration;if(!accountingEnabledFor(registration))return{error:reply({error:"Accounting is not included in this subscription."},403)};const entity=await loadAccountingEntityByParish(env,parishId);const registry=entity&&await loadAccountingDatabaseForEntity(env,entity.id,"production");if(!entity||entity.entityStatus!=="ready"||registry?.provisioningStatus!=="ready"||registry?.healthStatus!=="healthy")return{error:reply({error:"Accounting is not ready or did not pass its safety checks."},409)};const provider=await loadAccountingDatabaseProviderRecord(env,entity.id,"production"),adapter=createCloudflareD1ProvisioningAdapter(env),physical=await adapter.findByName(provider.databaseIdentifier);if(!physical)return{error:reply({error:"Accounting database is unavailable."},503)};return{db:createD1DatabaseFacade(adapter,physical.providerId),actor:{id:auth.user.id,type:"platform_user",capabilities:auth.capabilities||[]},tier:accountingTierFor(registration),databaseStatus:registry.provisioningStatus,databaseHealth:registry.healthStatus};}
export async function handleAccountingLedger(request,env,parishId){const url=new URL(request.url),base=`/api/parish/dashboard/${encodeURIComponent(parishId)}/accounting`,path=url.pathname.slice(base.length),match=path.match(/^\/journals(?:\/([^/]+))?(?:\/([^/]+))?$/);if(!url.pathname.startsWith(base))return null;let capability=request.method==="GET"?"accounting.view":"accounting.journals.create";if(match?.[2]==="post")capability="accounting.journals.post";try{const ctx=await accountingContext(request,env,parishId,capability);if(!ctx)return reply({error:"Unauthorized"},401);if(ctx.error)return ctx.error;const data=await request.json().catch(()=>({}));if(match){const id=match[1]?decodeURIComponent(match[1]):"",action=match[2]||"";if(request.method==="GET"&&!id)return reply({ok:true,tier:ctx.tier,entries:await searchJournalEntries(ctx.db,{actor:ctx.actor,query:url.searchParams.get("q")||"",status:url.searchParams.get("status")||"",sourceType:url.searchParams.get("sourceType")||"",dateFrom:url.searchParams.get("from")||"",dateTo:url.searchParams.get("to")||"",limit:url.searchParams.get("limit")||50,offset:url.searchParams.get("offset")||0})});if(request.method==="POST"&&!id)return reply({ok:true,entry:await createJournalDraft(ctx.db,{actor:ctx.actor,...data})},201);if(request.method==="GET"&&id&&!action)return reply({ok:true,entry:await getJournalEntry(ctx.db,{actor:ctx.actor,journalEntryId:id})});if(request.method==="PATCH"&&id)return reply({ok:true,entry:await updateJournalDraft(ctx.db,{actor:ctx.actor,journalEntryId:id,...data})});if(request.method==="POST"&&action==="validate")return reply({ok:true,validation:await validateJournalEntryForPosting(ctx.db,{journalEntryId:id,expectedVersion:data.expectedVersion})});if(request.method==="POST"&&action==="post")return reply({ok:true,entry:await postJournalEntry(ctx.db,{actor:ctx.actor,journalEntryId:id,...data})});}
const reg=path.match(/^\/(general-ledger|account-registers|fund-registers)(?:\/([^/]+))?$/);if(request.method==="GET"&&reg){const rows=await ledgerRegister(ctx.db,{actor:ctx.actor,accountId:reg[1]==="account-registers"?decodeURIComponent(reg[2]||""):"",fundId:reg[1]==="fund-registers"?decodeURIComponent(reg[2]||""):"",dateFrom:url.searchParams.get("from")||"",dateTo:url.searchParams.get("to")||""});return reply({ok:true,rows});}const exp=path.match(/^\/exports\/(general-ledger|accounts|funds)(?:\/([^/]+))?\.csv$/);if(request.method==="GET"&&exp){const rows=await ledgerRegister(ctx.db,{actor:ctx.actor,accountId:exp[1]==="accounts"?decodeURIComponent(exp[2]||""):"",fundId:exp[1]==="funds"?decodeURIComponent(exp[2]||""):""});return new Response(ledgerRegisterCsv(rows),{headers:{...HEADERS,"Content-Type":"text/csv; charset=utf-8","Content-Disposition":"attachment; filename=agapay-ledger.csv"}});}if(request.method==="GET"&&path==="/print/general-ledger"){const rows=await ledgerRegister(ctx.db,{actor:ctx.actor});return new Response(printableLedger(rows),{headers:{...HEADERS,"Content-Type":"text/html; charset=utf-8"}});}return reply({error:"Not found"},404);}catch(error){return reply({error:error?.details?.conflict?"conflict":"accounting_request_failed",message:error?.message||"Accounting request failed."},error?.details?.conflict?409:400);}}
