import { json } from "../lib/core.js";
import { createCloseSession, closeSessionDetail, validateCloseSession, waiveCloseCheck, reviewCloseSession, completeCloseSession, reopenCloseSession, previewYearEndClose, executeYearEndClose, auditReadiness, generateAccountantExport, closePacketHtml, auditTrailCsv } from "../accounting/index.js";
import { accountingContext } from "./accounting-ledger.js";

const HEADERS={"Cache-Control":"private, no-store","X-Robots-Tag":"noindex, nofollow",Vary:"Authorization"};
const reply=(payload,status=200)=>json(payload,{status,headers:HEADERS});
const tierOf=t=>t==="advanced_operations"?"parish":"mission";
const rows=async(db,sql,...params)=>(await db.prepare(sql).bind(...params).all()).results||[];
function required(path,method){if(path.includes("audit-trail"))return"accounting.audit_exports.generate";if(path.includes("accountant-export"))return"accounting.accountant_exports.generate";if(path.includes("/year-end/")&&path.endsWith("/execute"))return"accounting.year_end.execute";if(path.includes("year-end"))return"accounting.year_end.view";if(path.endsWith("/validate"))return"accounting.close.validate";if(path.endsWith("/waive"))return"accounting.close.review";if(path.endsWith("/review"))return"accounting.close.review";if(path.endsWith("/approve"))return"accounting.close.approve";if(path.endsWith("/complete"))return"accounting.close.complete";if(path.endsWith("/reopen"))return"accounting.close.reopen";if(path==="/close/sessions"&&method==="POST")return"accounting.close.create";return"accounting.close.view";}
export async function handleAccountingClose(request,env,parishId){const url=new URL(request.url),base=`/api/parish/dashboard/${encodeURIComponent(parishId)}/accounting`;if(!url.pathname.startsWith(base))return null;let path=url.pathname.slice(base.length);if(!path.startsWith("/close"))return null;try{const ctx=await accountingContext(request,env,parishId,required(path,request.method));if(!ctx)return reply({error:"Unauthorized"},401);if(ctx.error)return ctx.error;const tier=tierOf(ctx.tier),body=request.method==="GET"?{}:await request.json().catch(()=>({}));
  if(request.method==="GET"&&path==="/close/workspace")return reply({ok:true,fiscalYears:await rows(ctx.db,"SELECT id,name,start_date startDate,end_date endDate,status,version FROM accounting_fiscal_years ORDER BY start_date DESC"),periods:await rows(ctx.db,"SELECT id,fiscal_year_id fiscalYearId,name,start_date startDate,end_date endDate,status,version FROM accounting_periods ORDER BY start_date DESC"),sessions:await rows(ctx.db,"SELECT id,close_type closeType,fiscal_year_id fiscalYearId,accounting_period_id accountingPeriodId,status,last_validated_at lastValidatedAt,completed_at completedAt,version FROM accounting_close_sessions ORDER BY started_at DESC")});
  if(request.method==="POST"&&path==="/close/sessions")return reply({ok:true,session:await createCloseSession(ctx.db,{actor:ctx.actor,entitlementTier:tier,...body})},201);
  if(request.method==="GET"&&path==="/close/audit-trail.csv")return new Response(await auditTrailCsv(ctx.db,{actor:ctx.actor,entitlementTier:tier,startDate:url.searchParams.get("startDate")||"2000-01-01",endDate:url.searchParams.get("endDate")||"2099-12-31"}),{headers:{...HEADERS,"Content-Type":"text/csv; charset=utf-8","Content-Disposition":"attachment; filename=agapay-accounting-audit-trail.csv"}});
  const year=path.match(/^\/close\/year-end\/([^/]+)(?:\/(preview|execute|audit-readiness|accountant-export))?$/);if(year){const fiscalYearId=decodeURIComponent(year[1]),action=year[2];if(request.method==="GET"&&action==="preview")return reply({ok:true,preview:await previewYearEndClose(ctx.db,{actor:ctx.actor,entitlementTier:tier,fiscalYearId})});if(request.method==="GET"&&action==="audit-readiness")return reply({ok:true,readiness:await auditReadiness(ctx.db,{actor:ctx.actor,entitlementTier:tier,fiscalYearId})});if(request.method==="POST"&&action==="accountant-export")return reply({ok:true,export:await generateAccountantExport(ctx.db,{actor:ctx.actor,entitlementTier:tier,fiscalYearId,closeSessionId:body.closeSessionId||null})});if(request.method==="POST"&&action==="execute")return reply({ok:true,result:await executeYearEndClose(ctx.db,{actor:ctx.actor,entitlementTier:tier,closeSessionId:body.closeSessionId,expectedVersion:body.expectedVersion})});}
  const session=path.match(/^\/close\/sessions\/([^/]+)(?:\/(validate|waive|review|approve|complete|reopen|packet))?$/);if(session){const closeSessionId=decodeURIComponent(session[1]),action=session[2];if(request.method==="GET"&&!action)return reply({ok:true,session:await closeSessionDetail(ctx.db,{actor:ctx.actor,entitlementTier:tier,closeSessionId})});if(request.method==="GET"&&action==="packet")return new Response(await closePacketHtml(ctx.db,{actor:ctx.actor,entitlementTier:tier,closeSessionId}),{headers:{...HEADERS,"Content-Type":"text/html; charset=utf-8"}});const args={actor:ctx.actor,entitlementTier:tier,closeSessionId,expectedVersion:body.expectedVersion};if(request.method==="POST"&&action==="validate")return reply({ok:true,session:await validateCloseSession(ctx.db,args)});if(request.method==="POST"&&action==="waive")return reply({ok:true,check:await waiveCloseCheck(ctx.db,{...args,checkId:body.checkId,reason:body.reason})});if(request.method==="POST"&&["review","approve"].includes(action))return reply({ok:true,session:await reviewCloseSession(ctx.db,{...args,action})});if(request.method==="POST"&&action==="complete")return reply({ok:true,session:await completeCloseSession(ctx.db,args)});if(request.method==="POST"&&action==="reopen")return reply({ok:true,session:await reopenCloseSession(ctx.db,{...args,reason:body.reason})});}
  return reply({error:"Not found"},404);
}catch(error){const conflict=Boolean(error?.details?.conflict);return reply({error:conflict?"conflict":"accounting_request_failed",message:error?.message||"Accounting close request failed."},conflict?409:400);}}
