import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

// AGAPAY Learn renders print-shop PDFs server-side in the Cloudflare Worker.
// pdf-lib is pure JavaScript and Worker-compatible, so we avoid Puppeteer,
// Chromium, nodejs_compat, and browser print hacks. This is the intentional
// first dependency added to support real PDF generation.

const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const LETTER = [612, 792];
const MARGIN = 46;
const NAVY = rgb(0.02, 0.08, 0.15);
const NAVY_SOFT = rgb(0.06, 0.16, 0.24);
const GOLD = rgb(0.72, 0.55, 0.2);
const GOLD_SOFT = rgb(0.94, 0.86, 0.65);
const CREAM = rgb(0.98, 0.95, 0.88);
const PAPER = rgb(1, 0.99, 0.96);
const INK = rgb(0.08, 0.1, 0.14);
const MUTED = rgb(0.36, 0.38, 0.42);
const LINE = rgb(0.83, 0.78, 0.68);

function text(value) {
  return String(value ?? "").replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "-").trim();
}

function sumMinutes(minutes = []) {
  return minutes.reduce((sum, minute) => sum + Number(minute || 0), 0);
}

function childFormLabel(child = {}) {
  if (child.formLabel || child.gradeLabel || child.form) return child.formLabel || child.gradeLabel || child.form;
  const years = Number(child.ageYears);
  if (!Number.isFinite(years)) return "Household Form";
  if (years <= 5) return "Little Ones";
  if (years <= 8) return "Form I";
  if (years <= 11) return "Form II";
  if (years <= 14) return "Form III";
  if (years <= 16) return "Form IV";
  return "Form V";
}

function groupChildRowsByForm(childRows = []) {
  const groups = new Map();
  childRows.forEach((row) => {
    const label = childFormLabel(row.child);
    if (!groups.has(label)) {
      groups.set(label, {
        label,
        children: new Set(),
        details: [],
        minutes: 0
      });
    }
    const group = groups.get(label);
    if (row.child?.firstName) group.children.add(row.child.firstName);
    if (row.title) group.details.push(row.detail ? `${row.title}: ${row.detail}` : row.title);
    group.minutes += sumMinutes(row.minutes);
  });
  return Array.from(groups.values());
}

function findTemplate(printCenter, templateId) {
  const requested = templateId === "weekly-pack" ? "print_mom_weekly" : templateId;
  return printCenter.templates.find((template) => template.id === requested)
    || printCenter.templates.find((template) => template.id === "print_mom_weekly")
    || printCenter.templates[0]
    || { id: "print_mom_weekly", title: "Weekly Household Plan", templateType: "weekly-household-plan" };
}

function templateWithParams(template, params = {}) {
  return {
    ...template,
    childId: params.childId || template.childId || "",
    termId: params.termId || template.termId || "",
    month: params.month || template.month || "",
    year: params.year || template.year || ""
  };
}

function childForTemplate(printCenter, template) {
  if (template.child) return template.child;
  return printCenter.children.find((child) => child.id === template.childId) || null;
}

function tableSection(heading, columns, rows) {
  return {
    type: "table",
    heading,
    columns,
    rows: rows.filter((row) => row.some((cell) => text(cell)))
  };
}

function listSection(heading, items) {
  return {
    type: "list",
    heading,
    items: items.map((item) => typeof item === "string" ? { label: item, detail: "" } : item).filter((item) => text(item.label || item.detail))
  };
}

function cardsSection(heading, items) {
  return {
    type: "cards",
    heading,
    items: items.filter((item) => text(item.label || item.value || item.detail))
  };
}

function baseDocument(printCenter, template, generatedAt) {
  return {
    title: text(template.title || "AGAPAY Learn Print Pack"),
    subtitle: text(`${printCenter.household?.name || "Household"} - ${printCenter.term?.label || "Current Term"} - ${printCenter.week?.label || ""}`),
    generatedAt,
    templateId: template.id,
    sections: [],
    footerNote: "Generated by AGAPAY Learn"
  };
}

function buildHouseholdWeekly(printCenter, template, generatedAt) {
  const document = baseDocument(printCenter, template, generatedAt);
  const week = printCenter.week || {};
  const formRows = groupChildRowsByForm(week.childRows || []);
  document.sections = [
    tableSection("Household Stream", ["Rhythm", "Notes", "Minutes"], (week.householdRows || []).map((row) => [
      row.title,
      row.detail,
      `${sumMinutes(row.minutes)}m`
    ])),
    tableSection("Form Plans", ["Form", "Children", "Assignments"], formRows.map((row) => [
      row.label,
      Array.from(row.children).join(", "),
      row.details.slice(0, 5).join("; ")
    ])),
    listSection("Liturgical Notes", (week.liturgicalDays || []).slice(0, 7).map((day) => ({
      label: `${day.weekday || ""} ${day.date || ""}`.trim(),
      detail: [day.title, day.fastingRule, day.gospelRef].filter(Boolean).join(" - ")
    })))
  ];
  return document;
}

function buildTermPlan(printCenter, template, generatedAt) {
  const document = baseDocument(printCenter, template, generatedAt);
  const setup = printCenter.termSetup || {};
  const activeTerm = (setup.termOptions || []).find((term) => term.id === setup.activeTermId) || {};
  document.sections = [
    cardsSection("Current Term", [
      { label: "Term", value: activeTerm.label || printCenter.term?.label || "Current Term", detail: printCenter.term?.week || "" },
      { label: "Calendar", value: printCenter.calendarToggle?.label || "Orthodox Calendar", detail: printCenter.calendarToggle?.description || "" },
      { label: "Grace Mode", value: "Available", detail: "Use lighter weeks without losing the term rhythm." }
    ]),
    tableSection("Children and Forms", ["Child", "Form", "Age"], (printCenter.children || []).map((child) => [
      child.firstName || child.name,
      childFormLabel(child),
      child.ageYears ? `${child.ageYears}` : ""
    ])),
    tableSection("Term Options", ["Term", "Status", "Notes"], (setup.termOptions || []).map((term) => [
      term.label,
      term.id === setup.activeTermId ? "Current" : "Planned",
      term.startDate && term.endDate ? `${term.startDate} to ${term.endDate}` : "Set in Setup"
    ]))
  ];
  return document;
}

function buildMonthCalendar(printCenter, template, generatedAt) {
  const document = baseDocument(printCenter, template, generatedAt);
  const dates = printCenter.week?.dates || [];
  document.sections = [
    tableSection("Week View", ["Day", "Date", "Feast / Rhythm", "Plan"], dates.map((date, index) => {
      const liturgicalDay = (printCenter.week?.liturgicalDays || [])[index] || {};
      const householdPlan = (printCenter.week?.householdRows || [])
        .filter((row) => Number(row.minutes?.[index] || 0) > 0)
        .map((row) => row.title)
        .slice(0, 3)
        .join(", ");
      return [DAYS[index] || "", date, liturgicalDay.title || "", householdPlan];
    })),
    listSection("Upcoming Notes", (printCenter.week?.liturgicalDays || []).map((day) => ({
      label: day.title || day.date,
      detail: [day.fastingRule, day.epistleRef, day.gospelRef].filter(Boolean).join(" - ")
    })))
  ];
  return document;
}

function buildChildWeekly(printCenter, template, generatedAt) {
  const document = baseDocument(printCenter, template, generatedAt);
  const child = childForTemplate(printCenter, template);
  const rows = (printCenter.week?.childRows || []).filter((row) => !child?.id || row.childId === child.id);
  document.title = `${child?.firstName || "Child"}'s Weekly Sheet`;
  document.sections = [
    cardsSection("Student", [
      { label: "Name", value: child?.firstName || "Student", detail: childFormLabel(child || {}) },
      { label: "Week", value: printCenter.week?.label || "Current Week", detail: printCenter.term?.label || "" }
    ]),
    tableSection("Assignments", ["Subject", "Assignment", "Minutes"], rows.map((row) => [
      row.title,
      row.detail,
      `${sumMinutes(row.minutes)}m`
    ])),
    tableSection("Daily Checkboxes", ["Subject", "Mon", "Tue", "Wed", "Thu", "Fri"], rows.map((row) => [
      row.title,
      "[ ]",
      "[ ]",
      "[ ]",
      "[ ]",
      "[ ]"
    ])),
    listSection("Parent Notes", [
      "Narration:",
      "Copywork:",
      "Prayer and habit notes:"
    ])
  ];
  return document;
}

function buildChildTerm(printCenter, template, generatedAt) {
  const document = buildChildWeekly(printCenter, template, generatedAt);
  document.title = `${childForTemplate(printCenter, template)?.firstName || "Child"}'s Term Plan`;
  document.sections = [
    ...(buildTermPlan(printCenter, template, generatedAt).sections || []),
    ...(document.sections || []).slice(1, 3)
  ];
  return document;
}

export function buildWeeklyHouseholdPrintDocument({ household, week, calendarToggle }) {
  return buildHouseholdWeekly({
    household,
    week,
    calendarToggle,
    term: { label: week?.termLabel || "Current Term" },
    templates: []
  }, { id: "print_mom_weekly", title: "Weekly Household Plan" }, new Date().toISOString());
}

export function buildLearnPrintDocument(printCenter, { templateId = "print_mom_weekly", childId = "", termId = "", month = "", year = "", generatedAt = new Date().toISOString() } = {}) {
  const template = templateWithParams(findTemplate(printCenter, templateId), { childId, termId, month, year });
  const type = template.templateType || "weekly-household-plan";
  if (type === "term-plan" || template.id === "print_mom_term") return buildTermPlan(printCenter, template, generatedAt);
  if (type === "month-calendar" || template.id === "print_mom_month") return buildMonthCalendar(printCenter, template, generatedAt);
  if (type === "liturgical-school-calendar" || template.id === "print_mom_liturgical") return buildMonthCalendar(printCenter, template, generatedAt);
  if (type === "child-weekly-assignment") return buildChildWeekly(printCenter, template, generatedAt);
  if (type === "child-term-plan") return buildChildTerm(printCenter, template, generatedAt);
  return buildHouseholdWeekly(printCenter, template, generatedAt);
}

export function buildLearnReportPrintDocument(reports, { templateId = "year-end-report", label = "", generatedAt = new Date().toISOString() } = {}) {
  const normalized = text(templateId || label || "year-end-report").toLowerCase();
  const title = normalized.includes("transcript")
    ? "Academic Transcript"
    : normalized.includes("report-card") || normalized.includes("report card")
      ? "Term Report Card"
      : normalized.includes("subject")
        ? "Subject Progress Report"
        : label || "Year-End Report";
  const document = {
    title,
    subtitle: text(`${reports.household?.name || "Household"} - ${reports.schoolYear?.label || reports.term?.label || "School Year"}`),
    generatedAt,
    templateId,
    footerNote: "Generated by AGAPAY Learn",
    sections: []
  };

  const childRows = (reports.children || []).map((child) => [
    child.firstName || child.name,
    childFormLabel(child),
    child.ageYears ? `Age ${child.ageYears}` : "",
    child.summary || ""
  ]);
  const progressRows = (reports.subjectProgress || []).map((row) => [
    row.subjectTitle,
    row.childName,
    row.formLabel,
    `${row.completed} / ${row.total} ${row.progressionType || "units"}`,
    `${row.percent}%`,
    row.status
  ]);
  const narrationRows = (reports.narrationLogs || []).slice(0, 24).map((entry) => [
    entry.date,
    entry.child?.firstName || entry.childName || entry.childId || "",
    entry.source,
    entry.narrationType || entry.type || "",
    entry.note
  ]);

  if (normalized.includes("transcript")) {
    document.sections = [
      tableSection("Transcripts", ["Student", "Grade Span", "Credits", "Status"], (reports.transcripts || []).map((transcript) => [
        transcript.child?.firstName || transcript.childId || "",
        transcript.gradeSpan || "",
        transcript.credits || "",
        transcript.status || ""
      ])),
      tableSection("Transcript Records", ["Subject", "Mark", "Model"], (reports.transcripts || []).flatMap((transcript) =>
        (transcript.records || []).map((record) => [record.subject, record.mark, record.evaluationModel])
      ))
    ];
    return document;
  }

  if (normalized.includes("report-card") || normalized.includes("report card")) {
    document.sections = [
      tableSection("Report Cards", ["Student", "Summary", "Status"], (reports.reportCards || []).map((report) => [
        report.child?.firstName || report.childId || "",
        report.summary || "",
        report.status || ""
      ])),
      tableSection("Evaluation Records", ["Subject", "Mark", "Narrative"], (reports.reportCards || []).flatMap((report) =>
        (report.records || []).map((record) => [record.subject, record.mark, record.narrativeSummary])
      ))
    ];
    return document;
  }

  document.sections = [
    cardsSection("Summary", [
      { label: "School Year", value: reports.schoolYear?.label || "", detail: reports.term?.label || "" },
      { label: "Lessons", value: `${reports.weeklySummary?.lessonsCompleted || 0} / ${reports.weeklySummary?.lessonsPlanned || 0}`, detail: "Tracked weekly progress" },
      { label: "Children", value: String((reports.children || []).length), detail: "Students in this household" }
    ]),
    tableSection("Student Overview", ["Student", "Form", "Age", "Notes"], childRows),
    tableSection("Subject Progress", ["Subject", "Student", "Form", "Progress", "Complete", "Status"], progressRows),
    tableSection("Narration Log", ["Date", "Student", "Source", "Type", "Note"], narrationRows)
  ];
  return document;
}

export function buildPrintJobRequest({ templateId, format = "pdf", rangeLabel = "", requestedBy = "household" }) {
  return {
    templateId,
    format,
    rangeLabel,
    requestedBy,
    status: "ready",
    createdAt: new Date().toISOString()
  };
}

export function printDocumentFilename(document) {
  return `${text(document.title || "agapay-learn-print").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "agapay-learn-print"}.pdf`;
}

function wrapText(value, font, fontSize, maxWidth) {
  const words = text(value).split(/\s+/).filter(Boolean);
  const lines = [];
  let line = "";
  words.forEach((word) => {
    const next = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(next, fontSize) <= maxWidth || !line) {
      line = next;
    } else {
      lines.push(line);
      line = word;
    }
  });
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

function drawTextLines(page, lines, x, y, { font, size, color, leading = size + 4 }) {
  lines.forEach((line, index) => {
    page.drawText(line, { x, y: y - index * leading, size, font, color });
  });
  return y - lines.length * leading;
}

function fitPage(state, neededHeight) {
  if (state.y - neededHeight > MARGIN + 28) return;
  addPage(state);
}

function addPage(state) {
  const page = state.pdf.addPage(LETTER);
  page.drawRectangle({ x: 0, y: 0, width: LETTER[0], height: LETTER[1], color: PAPER });
  page.drawRectangle({ x: 0, y: LETTER[1] - 78, width: LETTER[0], height: 78, color: NAVY });
  page.drawText("AGAPAY LEARN", { x: MARGIN, y: LETTER[1] - 36, size: 11, font: state.fonts.helveticaBold, color: GOLD });
  page.drawText("Print Shop", { x: MARGIN, y: LETTER[1] - 55, size: 9, font: state.fonts.helvetica, color: CREAM });
  page.drawLine({ start: { x: MARGIN, y: LETTER[1] - 86 }, end: { x: LETTER[0] - MARGIN, y: LETTER[1] - 86 }, thickness: 1, color: GOLD });
  state.page = page;
  state.pages.push(page);
  state.y = LETTER[1] - 118;
}

function drawHeading(state, heading) {
  fitPage(state, 40);
  state.page.drawText(text(heading).toUpperCase(), { x: MARGIN, y: state.y, size: 10, font: state.fonts.helveticaBold, color: GOLD });
  state.y -= 17;
  state.page.drawLine({ start: { x: MARGIN, y: state.y }, end: { x: LETTER[0] - MARGIN, y: state.y }, thickness: 0.75, color: LINE });
  state.y -= 16;
}

function drawCards(state, section) {
  drawHeading(state, section.heading);
  const cardWidth = (LETTER[0] - MARGIN * 2 - 18) / 2;
  section.items.forEach((item, index) => {
    const x = MARGIN + (index % 2) * (cardWidth + 18);
    if (index % 2 === 0) fitPage(state, 78);
    const y = state.y;
    state.page.drawRectangle({ x, y: y - 58, width: cardWidth, height: 58, borderColor: LINE, borderWidth: 0.7, color: CREAM });
    state.page.drawText(text(item.label), { x: x + 10, y: y - 18, size: 9, font: state.fonts.helveticaBold, color: GOLD });
    state.page.drawText(text(item.value || ""), { x: x + 10, y: y - 35, size: 13, font: state.fonts.timesBold, color: NAVY });
    drawTextLines(state.page, wrapText(item.detail || "", state.fonts.helvetica, 7.5, cardWidth - 20).slice(0, 2), x + 10, y - 47, {
      font: state.fonts.helvetica,
      size: 7.5,
      color: MUTED,
      leading: 9
    });
    if (index % 2 === 1 || index === section.items.length - 1) state.y -= 74;
  });
}

function drawList(state, section) {
  drawHeading(state, section.heading);
  section.items.forEach((item) => {
    const lines = wrapText([item.label, item.detail].filter(Boolean).join(" - "), state.fonts.helvetica, 9, LETTER[0] - MARGIN * 2 - 22);
    fitPage(state, lines.length * 12 + 12);
    state.page.drawText("-", { x: MARGIN + 2, y: state.y, size: 9, font: state.fonts.helveticaBold, color: GOLD });
    state.y = drawTextLines(state.page, lines, MARGIN + 18, state.y, {
      font: state.fonts.helvetica,
      size: 9,
      color: INK,
      leading: 12
    }) - 4;
  });
  state.y -= 8;
}

function drawTable(state, section) {
  drawHeading(state, section.heading);
  const widths = section.columns.map((_, index) => {
    if (section.columns.length === 3) return [130, 300, 80][index];
    if (section.columns.length === 4) return [70, 90, 170, 180][index];
    if (section.columns.length === 6) return index === 0 ? 150 : 72;
    return (LETTER[0] - MARGIN * 2) / section.columns.length;
  });
  const drawHeader = () => {
    fitPage(state, 30);
    let x = MARGIN;
    state.page.drawRectangle({ x: MARGIN, y: state.y - 18, width: LETTER[0] - MARGIN * 2, height: 22, color: NAVY_SOFT });
    section.columns.forEach((column, index) => {
      state.page.drawText(text(column), { x: x + 5, y: state.y - 10, size: 7.5, font: state.fonts.helveticaBold, color: CREAM });
      x += widths[index];
    });
    state.y -= 25;
  };
  drawHeader();
  section.rows.forEach((row) => {
    const wrapped = row.map((cell, index) => wrapText(cell, state.fonts.helvetica, 8, widths[index] - 10).slice(0, 4));
    const rowHeight = Math.max(24, Math.max(...wrapped.map((lines) => lines.length)) * 10 + 10);
    if (state.y - rowHeight < MARGIN + 32) {
      addPage(state);
      drawHeader();
    }
    let x = MARGIN;
    state.page.drawRectangle({ x: MARGIN, y: state.y - rowHeight + 4, width: LETTER[0] - MARGIN * 2, height: rowHeight, borderColor: LINE, borderWidth: 0.4, color: rgb(1, 1, 0.98) });
    wrapped.forEach((lines, index) => {
      drawTextLines(state.page, lines, x + 5, state.y - 8, {
        font: state.fonts.helvetica,
        size: 8,
        color: INK,
        leading: 10
      });
      x += widths[index];
    });
    state.y -= rowHeight;
  });
  state.y -= 12;
}

function drawSection(state, section) {
  if (!section) return;
  if (section.type === "cards") return drawCards(state, section);
  if (section.type === "table") return drawTable(state, section);
  return drawList(state, section);
}

export async function renderPrintDocumentPdf(document) {
  const pdf = await PDFDocument.create();
  const fonts = {
    times: await pdf.embedFont(StandardFonts.TimesRoman),
    timesBold: await pdf.embedFont(StandardFonts.TimesRomanBold),
    helvetica: await pdf.embedFont(StandardFonts.Helvetica),
    helveticaBold: await pdf.embedFont(StandardFonts.HelveticaBold)
  };
  const state = { pdf, fonts, pages: [], page: null, y: 0 };
  addPage(state);

  const titleLines = wrapText(document.title, fonts.timesBold, 28, LETTER[0] - MARGIN * 2);
  state.y = drawTextLines(state.page, titleLines, MARGIN, state.y, {
    font: fonts.timesBold,
    size: 28,
    color: NAVY,
    leading: 31
  });
  state.y = drawTextLines(state.page, wrapText(document.subtitle, fonts.helvetica, 10, LETTER[0] - MARGIN * 2), MARGIN, state.y - 2, {
    font: fonts.helvetica,
    size: 10,
    color: MUTED,
    leading: 13
  }) - 18;
  state.page.drawLine({ start: { x: MARGIN, y: state.y + 8 }, end: { x: LETTER[0] - MARGIN, y: state.y + 8 }, thickness: 1.2, color: GOLD_SOFT });

  document.sections.forEach((section) => drawSection(state, section));

  state.pages.forEach((page, index) => {
    page.drawLine({ start: { x: MARGIN, y: 35 }, end: { x: LETTER[0] - MARGIN, y: 35 }, thickness: 0.6, color: LINE });
    page.drawText(document.footerNote || "Generated by AGAPAY Learn", {
      x: MARGIN,
      y: 20,
      size: 8,
      font: fonts.helvetica,
      color: MUTED
    });
    page.drawText(`Page ${index + 1} of ${state.pages.length}`, {
      x: LETTER[0] - MARGIN - 60,
      y: 20,
      size: 8,
      font: fonts.helvetica,
      color: MUTED
    });
  });

  return pdf.save();
}
